#!/usr/bin/env python3
"""Regenerate docs/reference/cli.md with current --help output and option tables.

Both the raw --help text and the formatted markdown tables are extracted from
the argparse parser definitions, so the docs stay in sync automatically.

Run via: uv run scripts/update-cli-reference.py
Exit code 0 if unchanged, 1 if updated (useful for pre-commit).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

DOCS_PATH = Path(__file__).resolve().parent.parent / "docs" / "reference" / "cli.md"

# Action types to skip when building tables.
_SKIP_TYPES = (argparse._HelpAction, argparse._VersionAction, argparse._SubParsersAction)


def _run_help(*args: str) -> str:
    result = subprocess.run(
        ["uv", "run", "credwolf", *args, "--help"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.rstrip()


def _format_flag(option_strings: Sequence[str]) -> tuple[str, str]:
    """Return (short, long) flag columns for a markdown table row."""
    short = ""
    long = ""
    for s in option_strings:
        if s.startswith("--"):
            long = f"`{s}`"
        else:
            short = f"`{s}`"
    return short, long


def _extract_actions(parser: argparse.ArgumentParser) -> list[tuple[str, list[argparse.Action]]]:
    """Extract actions grouped by argument group title.

    Returns a list of (group_title, actions) pairs.  Actions that should be
    skipped (help, version, subparsers) are filtered out.
    """
    groups: list[tuple[str, list[argparse.Action]]] = []
    for group in parser._action_groups:
        actions = [a for a in group._group_actions if not isinstance(a, _SKIP_TYPES)]
        if actions:
            groups.append((group.title or "options", actions))
    return groups


def _actions_to_table(actions: list[argparse.Action]) -> str:
    """Render a list of argparse actions as a markdown table."""
    rows = ["| Short | Long | Description |", "|-------|------|-------------|"]
    for action in actions:
        short, long = _format_flag(action.option_strings)
        desc = (action.help or "").replace("|", "\\|")
        # Capitalize first letter for consistency.
        if desc and desc[0].islower():
            desc = desc[0].upper() + desc[1:]
        rows.append(f"| {short} | {long} | {desc} |")
    return "\n".join(rows)


def _build_tables() -> dict[str, str]:
    """Import the CLI parser and build markdown tables for each section."""
    from credwolf.cli import _build_parser

    root, ntlm, kerberos, userenum = _build_parser()

    sections: dict[str, str] = {}

    # Global options — from the root parser, skip subparser action.
    global_groups = _extract_actions(root)
    global_actions = []
    for _title, actions in global_groups:
        global_actions.extend(actions)
    sections["global"] = _actions_to_table(global_actions)

    # Subcommand tables — one section per argument group.
    for name, parser in [("ntlm", ntlm), ("kerberos", kerberos), ("userenum", userenum)]:
        grouped = _extract_actions(parser)
        parts = []
        for title, actions in grouped:
            table = _actions_to_table(actions)
            parts.append(f"**{title.capitalize()}**\n\n{table}")
        sections[name] = "\n\n".join(parts)

    return sections


def generate() -> str:
    main_help = _run_help()
    ntlm_help = _run_help("ntlm")
    kerberos_help = _run_help("kerberos")
    userenum_help = _run_help("userenum")

    tables = _build_tables()

    return f"""\
# CLI reference

<!-- AUTO-GENERATED by scripts/update-cli-reference.py — do not edit manually -->

## Global options

{tables["global"]}

## NTLM options

{tables["ntlm"]}

## Kerberos options

{tables["kerberos"]}

## Username enumeration options

{tables["userenum"]}

## Full `--help` output

### `credwolf`

```
{main_help}
```

### `credwolf ntlm`

```
{ntlm_help}
```

### `credwolf kerberos`

```
{kerberos_help}
```

### `credwolf userenum`

```
{userenum_help}
```
"""


def main() -> int:
    new_content = generate()
    if DOCS_PATH.exists() and DOCS_PATH.read_text() == new_content:
        return 0
    DOCS_PATH.write_text(new_content)
    print(f"Updated {DOCS_PATH}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
